[package]
name = "keepass"
description = "KeePass .kdbx database file parser"

homepage = "https://github.com/sseemayer/keepass-rs"
repository = "https://github.com/sseemayer/keepass-rs"
documentation = "https://sseemayer.github.io/keepass-rs/"

version = "0.4.6"
authors = ["Stefan Seemayer <stefan@seemayer.de>"]
license = "MIT"

readme = "README.md"

[dependencies]
byteorder = "1"
flate2 = "1"
secstr = "0.4"
xml-rs = "0.8"
base64 = "0.12"
hex-literal = "0.2.0"
rust-argon2 = "0.8.1"
sha2 = "0.8.0"
aes = "0.3.2"
block-modes = "0.3.3"
hmac = "0.7.0"
salsa20 = "0.4"
chacha20 = "0.3"
stream-cipher = "0.3.2"
generic-array = "0.12"
twofish = "0.2.0"
